server:
  port: 8081
  context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_spring
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

